services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html