services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"

  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "8080:80"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html