-- Tabela de usuários
CREATE TABLE USUARIO (
    ID SERIAL PRIMARY KEY,
    NOME_USUARIO VARCHAR(255) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    PAPEL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE
);

-- Tabela para clientes, que herda de USUARIO
CREATE TABLE CLIENTE (
    ID INT PRIMARY KEY REFERENCES USUARIO(ID) ON DELETE CASCADE,
    CARTAO_CREDITO VARCHAR(20)
);

-- Tabela para fornecedores, que herda de USUARIO
CREATE TABLE FORNECEDOR (
    ID INT PRIMARY KEY REFERENCES USUARIO(ID) ON DELETE CASCADE,
    DESCRICAO TEXT
);

-- Tabela de produtos
CREATE TABLE produto (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT NOT NULL,
    fornecedor_id INT NOT NULL REFERENCES fornecedor(id) ON DELETE CASCADE,
    foto VARCHAR(255)
);

-- Tabela de estoque
CREATE TABLE ESTOQUE (
    ID SERIAL PRIMARY KEY,
    PRODUTO_ID INT NOT NULL REFERENCES PRODUTO(ID) ON DELETE CASCADE,
    QUANTIDADE INT NOT NULL CHECK (QUANTIDADE >= 0),
    PRECO DECIMAL(10, 2) NOT NULL CHECK (PRECO >= 0)
);

-- Tabela de pedidos
CREATE TABLE PEDIDO (
    ID SERIAL PRIMARY KEY,
    NUMERO VARCHAR(50) NOT NULL UNIQUE,
    CLIENTE_ID INT NOT NULL REFERENCES CLIENTE(ID) ON DELETE CASCADE,
    DATA_PEDIDO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_ENTREGA DATE,
    SITUACAO VARCHAR(50) NOT NULL DEFAULT 'PENDENTE',
    CONFIRMADO BOOLEAN NOT NULL DEFAULT FALSE,
    VALOR_TOTAL DECIMAL(10, 2) NOT NULL DEFAULT 0.00
);

-- Tabela de itens do pedido (relação produto-pedido)
CREATE TABLE ITEM_PEDIDO (
    ID SERIAL PRIMARY KEY,
    PEDIDO_ID INT NOT NULL REFERENCES PEDIDO(ID) ON DELETE CASCADE,
    PRODUTO_ID INT NOT NULL REFERENCES PRODUTO(ID) ON DELETE CASCADE,
    QUANTIDADE INT NOT NULL CHECK (QUANTIDADE > 0),
    PRECO_UNITARIO DECIMAL(10, 2) NOT NULL CHECK (PRECO_UNITARIO >= 0),
    SUBTOTAL DECIMAL(10, 2) NOT NULL CHECK (SUBTOTAL >= 0),
    UNIQUE(PEDIDO_ID, PRODUTO_ID)
);

-- Inserção de um usuário administrador
INSERT INTO USUARIO (NOME_USUARIO, SENHA, NOME, PAPEL, TELEFONE, EMAIL)
VALUES ('admin', '123123', 'Administrador', 'admin', '123456789', 'admin@example.com');