-- Tabela de usuários
CREATE TABLE USUARIO (
    ID SERIAL PRIMARY KEY,
    NOME_USUARIO VARCHAR(255) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    PAPEL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE
);

-- Tabela para clientes, que herda de USUARIO
CREATE TABLE CLIENTE (
    ID INT PRIMARY KEY REFERENCES USUARIO(ID) ON DELETE CASCADE,
    CARTAO_CREDITO VARCHAR(20)
);

-- Tabela para fornecedores, que herda de USUARIO
CREATE TABLE FORNECEDOR (
    ID INT PRIMARY KEY REFERENCES USUARIO(ID) ON DELETE CASCADE,
    DESCRICAO TEXT
);

-- Tabela de produtos
CREATE TABLE produto (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT NOT NULL,
    fornecedor_id INT NOT NULL REFERENCES fornecedor(id) ON DELETE CASCADE
);

-- Tabela de estoque
CREATE TABLE ESTOQUE (
    ID SERIAL PRIMARY KEY,
    PRODUTO_ID INT NOT NULL REFERENCES PRODUTO(ID) ON DELETE CASCADE,
    QUANTIDADE INT NOT NULL CHECK (QUANTIDADE >= 0),
    PRECO DECIMAL(10, 2) NOT NULL CHECK (PRECO >= 0)
);

-- Inserção de um usuário administrador
INSERT INTO USUARIO (NOME_USUARIO, SENHA, NOME, PAPEL, TELEFONE, EMAIL)
VALUES ('admin', '123123', 'Administrador', 'admin', '123456789', 'admin@example.com');