CREATE TABLE USUARIO (
    ID SERIAL PRIMARY KEY,
    NOME_USUARIO VARCHAR(255) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    PAPEL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE
);

-- Tabela para clientes, que herda de USUARIO
CREATE TABLE CLIENTE (
    ID SERIAL PRIMARY KEY,
    USUARIO_ID INT NOT NULL REFERENCES USUARIO(ID) ON DELETE CASCADE,
    CARTAO_CREDITO VARCHAR(20)
);

-- Tabela para fornecedores, que herda de USUARIO
CREATE TABLE FORNECEDOR (
    ID SERIAL PRIMARY KEY,
    USUARIO_ID INT NOT NULL REFERENCES USUARIO(ID) ON DELETE CASCADE,
    DESCRICAO TEXT
);

-- Insert an admin user
INSERT INTO USUARIO (NOME_USUARIO, SENHA, NOME, PAPEL, TELEFONE, EMAIL)
VALUES ('admin', '123123', 'Administrador', 'admin', '123456789', 'admin@example.com');